### ISSUE TITLE
A small mistake

### ISSUE THREAD

**Issue by ohohok** [XCanG/fastapi-rabbitmq#1]
Dockerfile ,not Dokerfile bro

**Comment by XCanG** [comment]
Oh, yes, thanks for pointing out. I wasn't actually being able to test Docker at time I creating this, so this mistake was not detected.
Closed in commit: https://github.com/XCanG/fastapi-rabbitmq/commit/7c380cd237aa18a5239229739ddfc6b853b1b39c

_By the way. It may require additional tweaks in Dockerfile, as I pointed above. In theory it should work, but not tested._
